import fs from 'fs'
import path from 'path'
import { SVG_DICTIONARY } from '../src/avatar/svgDictionary.full.js'

// Match any floating point number, including scientific notations
const floatRegex = /-?\d+\.\d+(?:[eE]-?\d+)?/g

function roundMatch(match) {
  const val = parseFloat(match)
  if (Math.abs(val) < 0.001) {
    return '0'
  }
  const rounded = Math.round(val * 10) / 10
  return String(rounded)
}

function compressValue(v) {
  if (typeof v === 'string') {
    return v.replace(floatRegex, roundMatch)
  }
  if (typeof v === 'number') {
    if (Math.abs(v) < 0.001) {
      return 0
    }
    return Math.round(v * 10) / 10
  }
  return v
}

function compressNode(node) {
  if (!node || typeof node !== 'object') {
    return node
  }

  const newNode = {}
  
  // Support both expanded and shorthand keys
  const type = node.t !== undefined ? node.t : node.type
  const props = node.p !== undefined ? node.p : node.props
  const children = node.c !== undefined ? node.c : node.children

  if (type !== undefined) {
    newNode.t = type
  }

  if (props && typeof props === 'object') {
    newNode.p = {}
    for (const [key, val] of Object.entries(props)) {
      if (key === 'style' && val && typeof val === 'object') {
        newNode.p[key] = {}
        for (const [sk, sv] of Object.entries(val)) {
          newNode.p[key][sk] = compressValue(sv)
        }
      } else {
        newNode.p[key] = compressValue(val)
      }
    }
  }

  if (Array.isArray(children)) {
    newNode.c = children.map(compressNode)
  }

  return newNode
}

// Ensure the target directory for split pieces exists
const piecesDir = 'src/avatar/pieces'
if (!fs.existsSync(piecesDir)) {
  fs.mkdirSync(piecesDir, { recursive: true })
}

const categoryFilenames = {
  BACKDROP: 'backdrop',
  CLOTHES: 'clothes',
  MOUTH: 'mouth',
  NOSE: 'nose',
  EYES: 'eyes',
  EYEBROW: 'eyebrow',
  ACCESSORIES: 'accessories',
  TOP: 'top',
  FACIAL_HAIR: 'facialHair'
}

// Deeply compress categories and write them to separate files
for (const [category, items] of Object.entries(SVG_DICTIONARY)) {
  const compressedCategory = {}
  for (const [itemName, itemRoot] of Object.entries(items)) {
    compressedCategory[itemName] = compressNode(itemRoot)
  }
  
  const filename = categoryFilenames[category]
  if (!filename) {
    console.error(`Error: Unknown category ${category}`)
    continue
  }
  
  const serialized = JSON.stringify(compressedCategory)
  const pieceContent = `// Automatically compressed by scripts/compress.js. Do not edit directly!\nexport default ${serialized};\n`
  fs.writeFileSync(path.join(piecesDir, `${filename}.js`), pieceContent, 'utf8')
}

// Generate the loader/proxy file src/avatar/svgDictionary.js
const loaderContent = `// Automatically generated by scripts/compress.js. Do not edit directly!

const categoryModules = {
  BACKDROP: () => import('./pieces/backdrop.js'),
  CLOTHES: () => import('./pieces/clothes.js'),
  MOUTH: () => import('./pieces/mouth.js'),
  NOSE: () => import('./pieces/nose.js'),
  EYES: () => import('./pieces/eyes.js'),
  EYEBROW: () => import('./pieces/eyebrow.js'),
  ACCESSORIES: () => import('./pieces/accessories.js'),
  TOP: () => import('./pieces/top.js'),
  FACIAL_HAIR: () => import('./pieces/facialHair.js')
};

const loadedCategories = {};

export async function loadCategories(categories) {
  await Promise.all(
    categories.map(async (cat) => {
      if (loadedCategories[cat]) return;
      if (!categoryModules[cat]) return;
      const mod = await categoryModules[cat]();
      loadedCategories[cat] = mod.default || mod;
    })
  );
}

export const SVG_DICTIONARY = new Proxy({}, {
  get(target, category) {
    return loadedCategories[category];
  }
});
`

fs.writeFileSync('src/avatar/svgDictionary.js', loaderContent, 'utf8')
console.log('SVG dictionary split and loader generated successfully!')
