// Automatically generated by scripts/compress.js. Do not edit directly!

const categoryModules = {
  BACKDROP: () => import('./pieces/backdrop.js'),
  CLOTHES: () => import('./pieces/clothes.js'),
  MOUTH: () => import('./pieces/mouth.js'),
  NOSE: () => import('./pieces/nose.js'),
  EYES: () => import('./pieces/eyes.js'),
  EYEBROW: () => import('./pieces/eyebrow.js'),
  ACCESSORIES: () => import('./pieces/accessories.js'),
  TOP: () => import('./pieces/top.js'),
  FACIAL_HAIR: () => import('./pieces/facialHair.js')
};

const loadedCategories = {};

export async function loadCategories(categories) {
  await Promise.all(
    categories.map(async (cat) => {
      if (loadedCategories[cat]) return;
      if (!categoryModules[cat]) return;
      const mod = await categoryModules[cat]();
      loadedCategories[cat] = mod.default || mod;
    })
  );
}

export const SVG_DICTIONARY = new Proxy({}, {
  get(target, category) {
    return loadedCategories[category];
  }
});
